#!/bin/sh

if [ $1 ]; then
    file=$1
    echo "发布类型: 正式版"
    echo "发布文件：fanfou.apk"
    scp $file sankuai@58.83.129.16:/opt/sankuai/apps.fanfou.com/android/fanfou.apk
    echo "发布文件：update.json"
    scp update.json sankuai@58.83.129.16:/opt/sankuai/apps.fanfou.com/android/
    echo "文件已成功发布到下载站点."
else
    echo "未指定要发布的文件"
fi

